### ISSUE TITLE
EVENT: Anmeldebestätigung (PDF) in Hitobito 

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_youth#85]
In unserer hitobito-Instanz und täglichen Arbeit ist uns aufgefallen, dass die Anmeldebestätigung (PDF "Drucken", Anmeldung bearbeiten) nicht über die Applikation (Hitobito) für das Profil erreichbar ist (siehe [Erkenntnisse](https://github.com/hitobito/hitobito/issues/2837#issuecomment-2346019478)). 
(Die Anmeldebestätigung wird lediglich als E-Mail-Anhang verschickt und im E-Mail-Text als {application-url} verlinkt)

~~Aktuell ist es zudem so, dass mit dem Feature Elternzugang aktuell die E-Mail nur an das Kind versendet wird. 
https://github.com/hitobito/hitobito/issues/2392#issuecomment-2352199182~~ 

Dieses Dokument ist im Alltag für unsere Mitglieder wichtig, da die Anmeldebestätigung oft wichtige Informationen beinhaltet, unterschrieben werden muss oder an den Anlass mitgebracht werden muss. 

Daher haben wir überlegt, dass die Anmeldebestätigung (PDF) auch zusätzlich direkt über die Applikation (Hitobito) aufrufbar sein sollte. Idealerweise hat auch die Profilverwalter*in (Elternzugang) die Möglichkeit die Anmeldebestätigung (PDF) für die verwalteten Profile aufrufen.

![image](https://github.com/user-attachments/assets/568d050c-eaa9-4290-a057-74f28cbb7353)

Was meint die Community dazu?

# ToDo, um die Diskussion zu starten

- [ ] andere Organisationen hier erwähnen (@ und github-usernamen)

# ToDo, nachdem die Diskussion ein Ergebnis hat

- [ ] Diskussionsergebnisse zusammenfassen
- [ ] Issue für Umsetzung erstellen
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by ThomasEllenberger** [comment]
@richardjubla Wir haben uns dies einmal angeschaut.
Eine Lösung, welche einfach umzusetzen und stark Core-Verträglich ist sehen wir wie folgt:

Wir fügen auf dem Aside der Person bei den nächsten Anlässen einen Button ein, welcher einem zur eigenen Anmeldung führt:
![grafik](https://github.com/user-attachments/assets/95c33022-649a-4ba0-9fef-186a71192b26)
Durch cklick auf den Button landet man bei der eigenen Anmeldung und sieht da gleich alle Optionen welche man für diesen Anlass hat (Abhängig von Berechtigung oder Anlasseinstellungen)
![grafik](https://github.com/user-attachments/assets/b98bec21-5114-4f84-9c39-5f09e7e830fa)

So erstellen wir keine zusätzliche Logik für das Drucken des Formulars, sondern nur einen Link auf eine Ansicht die man selbst bereits sehen könnte (wenn man den Link kennt, oder die Teilnehmenden des Anlasses sehen darf). Auch kann jede Person gleich alle Funktionen sehen welche sie in Zusammenhang mit dem Event ausführen kann. Damit sind auch Funktionen welche in anderen Wagons noch zusätzlich sind bereits abgefangen.

**Comment by richardjubla** [comment]
> @richardjubla Wir haben uns dies einmal angeschaut. Eine Lösung, welche einfach umzusetzen und stark Core-Verträglich ist sehen wir wie folgt:
> 

Sieht aus meiner Sicht gut aus. Da einfach und insb. "Core-Verträglich" gerne umsetzten.

**Comment by diegosteiner** [comment]
Ich schlage noch folgende Ergänzung vor:

Wenn ich auf einem Event angemeldet bin und ich auf diesen Event gehe, erscheint immer der Anmelde-Knopf. Ich habe im Kopf, dass dies auch schon als Bug gemeldet wurde. Ich würde diesen dann gleich mit dem Knopf zur Anmeldung ersetzen:

![image](https://github.com/user-attachments/assets/c4f1804f-d891-4b5f-9de7-cc6a9f98a05b)

**Comment by richardjubla** [comment]
> Ich schlage noch folgende Ergänzung vor:
> 
> Wenn ich auf einem Event angemeldet bin und ich auf diesen Event gehe, erscheint immer der Anmelde-Knopf. Ich habe im Kopf, dass dies auch schon als Bug gemeldet wurde. Ich würde diesen dann gleich mit dem Knopf zur Anmeldung ersetzen:
> 


Beachten wenn das weiterhilft: Der Anmelde-Knopf wurde mit dem Verwalter*innen Profil etwas komplexer. 

![image](https://github.com/user-attachments/assets/41d960ca-2592-410c-9d7e-ac72fbeeee25)

**Comment by ThomasEllenberger** [comment]
@diegosteiner Der Bug auf welchen du referenzierst ist vermutlich https://github.com/hitobito/hitobito/issues/2301

Richi hat Recht, dass dies im Youth-Wagon durch den Elternzugang komplizierter wurde. Auch wenn man selbst angemeldet ist, sollte man anschliessend noch seine Kinder anmelden können.
In manchen Wagons kann man sogar wenn alle angemeldet sind neue Kinder direkt erfassen und anmelden, da muss dieser Button also immer interagierbar sein, unabhängig vom eigenen Anmeldestatus oder auch dem bereits existierender Kinder-Accounts.

Da dies meines Erachtens ein ziemlich e zusätzliche Komplexität mit sich bringt, würde ich dies nicht im Umfang dieses Issues anschauen.

**Comment by diegosteiner** [comment]
@ThomasEllenberger 

> Da dies meines Erachtens eine ziemliche zusätzliche Komplexität mit sich bringt, würde ich dies nicht im Umfang dieses Issues anschauen.

Alles klar, ich konzentriere mich auf das was hier beschrieben ist.

---

Hier mein erster Entwurf :

![Image](https://github.com/user-attachments/assets/551b42f5-20eb-4be3-be62-105e376f6f16)

Was meint ihr @richardjubla, @ThomasEllenberger ? Ich bin noch nicht überzeugt von der Anordnung, aber bessere Vorschläge habe ich auch nicht wirklich. Eine Option wäre aber noch das hier:

![Image](https://github.com/user-attachments/assets/8bcc34d8-05d3-43ff-b3cf-fa58f1cc88df)

**Comment by nchiapol** [comment]
Ein spontaner Gedanke: Weshalb ersetzen wir unter "Meine nächsten Anlässe" nicht den bestehenden Link zum Anlass (also im Screenshot z.B "Anlass 303" oder "SLK 228") durch einen Link zur Anmeldung? 

Von der Anmeldung komme ich trivial zu den Anlass-Details...

**Comment by diegosteiner** [comment]
> Ein spontaner Gedanke: Weshalb ersetzen wir unter "Meine nächsten Anlässe" nicht den bestehenden Link zum Anlass (also im Screenshot z.B "Anlass 303" oder "SLK 228") durch einen Link zur Anmeldung?
> 
> Von der Anmeldung komme ich trivial zu den Anlass-Details...

Mir gefällt diese Variante auch sehr gut

**Comment by ThomasEllenberger** [comment]
@diegosteiner da uns @richardjubla hierzu auch einen Daumen hoch gegeben hat, würde ich das so umsetzen.

Da wir dies im Core umsetzen wollen, habe ich noch kurz im SAC-Wagon geteste, wie es sich dort verhällt, damit wir hoffentlich nichts kaputt machen.
Dabei ist mir aufgefallen dass dies im SAC-Wagon bereits genau so funktioniert!
Entsprechend würde ich dafür plädieren die Lösung vom SAC-Wagon in den Core zu verschieben anstatt dass wir da dann zwei separate Lösungen haben.

@diegosteiner kannst du nachvollziehen wann/wie das beim SAC gelöst wurde? Sonnst gerne mit einem Dev kurzschliessen. Ich konnte anhand der Github-Issues gerade nicht das korrekte Issue finden.

**Comment by ThomasEllenberger** [comment]
Wir haben das soeben noch etwas intensiver getestet:
1. Ich lag falsch, beim SAC ist das noch nicht gelöst. Wenn man an einen Anlass erst angemeldet, aber noch nicht zugeteilt ist landet man auf der Anmeldung, dies ist jedoch im Core so nicht nur bei SAC, und eben auch nicht sobald man Teilnehmer ist.

2. 
> Ein spontaner Gedanke: Weshalb ersetzen wir unter "Meine nächsten Anlässe" nicht den bestehenden Link zum Anlass (also im Screenshot z.B "Anlass 303" oder "SLK 228") durch einen Link zur Anmeldung?
> 
> Von der Anmeldung komme ich trivial zu den Anlass-Details...

@nchiapol 
Gerade bei der Cevi sehe ich den Anlass nicht immer. Melde ich mich als externer an und habe nur eine Eventrolle sehe ich auf der Anmeldeübersicht den Event nicht.. habe also keine Möglichkeit von da auf den Event zu navigieren.
![grafik](https://github.com/user-attachments/assets/9cc60e51-c704-4259-af28-746c400d2185)
Die Jubla umgeht dieses Problem, indem bei ihnen jeder der sich anmeldet auch eine Rolle Externer in der jeweiligen Schar erhält...

@richardjubla & @nchiapol Wir haben uns deshalb nun dazu entschieden, dies wie ursprünglich spezifiziert umzusetzen, mit einem zusätzlichen Link unter dem Anlass. Auf Input unseres UX-Mitarbeiters machen wir jedoch keinen Button , sondern einen Text, analog dem Eventname mit "Meine Anmeldung".

**Comment by richardjubla** [comment]
Wir sehen die Umsetzung bereits auf der produktiven Umgebung, was uns vom Ablauf her irritiert. Es gibt auch keinen Changelog-Eintrag dazu? Wie könne/sollen wir das Abnehmen? @ThomasEllenberger

**Comment by ThomasEllenberger** [comment]
@richardjubla 
Dieser Change ist bei uns offenbar durch den Mergefreeze gerutscht und durch den Hotfix-Release von dieser Woche auf eurer Produktiv-Umgebung gelandet. Das hätte nicht passieren sollen.
Mein Vorschlag ist: Ihr testet dies möglichst zeitnah auf eurer Integration. Ist alles in Ordnung können wir dies auch so auf der Produktionsumgebung belassen. Sollte etwas nicht wie gewünscht funktionieren, machen wir den Change rückgängig und releasen diesen erst später wider, sobald die nacharbeiten abgeschlossen sind.
Das Changelog werden wir nachliefern.

**Comment by richardjubla** [comment]
> @richardjubla Mein Vorschlag ist: Ihr testet dies möglichst zeitnah auf eurer Integration. Ist alles in Ordnung können wir dies auch so auf der Produktionsumgebung belassen. 

Danke für die Info. Ein kurzer Test gibt Vertrauen. Wir sehen uns das noch etwas genauer an. 
(Ehrlicherweise sind wir in diesem Fall ja schon etwas froh, ist es gleich auf produktiv.... ;-))
